apiVersion: v1
kind: Secret
metadata:
  name: bot-secrete
  namespace: demo
type: Opaque
stringData:
  BOT_KEY: ""
  BOT_PEPPER: ""
  
  # WEB Server info
  WEB_KEY: ""
  WEB_PEPPER: ""
  
  # API Server info
  API_USER: ""
  API_PASS: ""
  API_PEPPER: ""
  
  
  BOT_APPLICATION_ID: ""
  DISCORD_GENERAL_CH: ""
  DISCORD_TOKEN: ""
  
  REDDIT_USER: ""
  REDDIT_PASS: ""
  REDDIT_ID: ""
  REDDIT_SECRET: ""